# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Dec  8 10:22:54 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(793, 614)
        mainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblComments = QtGui.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tblComments.setFont(font)
        self.tblComments.setAutoFillBackground(False)
        self.tblComments.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tblComments.setFrameShadow(QtGui.QFrame.Sunken)
        self.tblComments.setLineWidth(1)
        self.tblComments.setMidLineWidth(0)
        self.tblComments.setAutoScroll(True)
        self.tblComments.setAlternatingRowColors(True)
        self.tblComments.setShowGrid(True)
        self.tblComments.setGridStyle(QtCore.Qt.NoPen)
        self.tblComments.setRowCount(0)
        self.tblComments.setColumnCount(6)
        self.tblComments.setObjectName("tblComments")
        self.tblComments.setColumnCount(6)
        self.tblComments.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(5, item)
        self.tblComments.horizontalHeader().setVisible(True)
        self.tblComments.horizontalHeader().setCascadingSectionResizes(True)
        self.tblComments.horizontalHeader().setDefaultSectionSize(100)
        self.tblComments.horizontalHeader().setHighlightSections(True)
        self.tblComments.horizontalHeader().setStretchLastSection(True)
        self.tblComments.verticalHeader().setVisible(False)
        self.tblComments.verticalHeader().setSortIndicatorShown(True)
        self.tblComments.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tblComments)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(mainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionHello = QtGui.QAction(mainWindow)
        self.actionHello.setObjectName("actionHello")
        self.actionRefresh = QtGui.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/arrow_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionConnection = QtGui.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnection.setIcon(icon1)
        self.actionConnection.setObjectName("actionConnection")
        self.actionPreferences = QtGui.QAction(mainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/cog_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon2)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtGui.QAction(mainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtGui.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/door_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon4)
        self.actionClose.setObjectName("actionClose")
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnection)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(mainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("activated()"), mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "WordPress Comments Desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.setSortingEnabled(True)
        self.tblComments.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("mainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("mainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("mainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("mainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("mainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("mainWindow", "Post Title", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("mainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHello.setText(QtGui.QApplication.translate("mainWindow", "Hello", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("mainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setToolTip(QtGui.QApplication.translate("mainWindow", "Refresh Comment list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnection.setText(QtGui.QApplication.translate("mainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnection.setToolTip(QtGui.QApplication.translate("mainWindow", "Edit Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("mainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setToolTip(QtGui.QApplication.translate("mainWindow", "Edit Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("mainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setToolTip(QtGui.QApplication.translate("mainWindow", "About WPC Desk", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("mainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setToolTip(QtGui.QApplication.translate("mainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

