# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Sat Jul 28 21:24:16 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_formConfig(object):
    def setupUi(self, formConfig):
        formConfig.setObjectName("formConfig")
        formConfig.setWindowModality(QtCore.Qt.ApplicationModal)
        formConfig.resize(465, 259)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(formConfig.sizePolicy().hasHeightForWidth())
        formConfig.setSizePolicy(sizePolicy)
        formConfig.setMinimumSize(QtCore.QSize(465, 259))
        formConfig.setMaximumSize(QtCore.QSize(465, 259))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/chat-quotes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        formConfig.setWindowIcon(icon)
        self.btnClose = QtGui.QPushButton(formConfig)
        self.btnClose.setGeometry(QtCore.QRect(260, 220, 85, 27))
        self.btnClose.setObjectName("btnClose")
        self.btnSave = QtGui.QPushButton(formConfig)
        self.btnSave.setGeometry(QtCore.QRect(360, 220, 85, 27))
        self.btnSave.setObjectName("btnSave")
        self.widget = QtGui.QWidget(formConfig)
        self.widget.setGeometry(QtCore.QRect(11, 12, 441, 201))
        self.widget.setObjectName("widget")
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.serverEdit = QtGui.QLineEdit(self.widget)
        self.serverEdit.setObjectName("serverEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.serverEdit)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.usernameEdit = QtGui.QLineEdit(self.widget)
        self.usernameEdit.setObjectName("usernameEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.usernameEdit)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.passEdit = QtGui.QLineEdit(self.widget)
        self.passEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.passEdit.setAutoFillBackground(False)
        self.passEdit.setInputMask("")
        self.passEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passEdit.setObjectName("passEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.passEdit)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.nameEdit = QtGui.QLineEdit(self.widget)
        self.nameEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.nameEdit.setAutoFillBackground(False)
        self.nameEdit.setInputMask("")
        self.nameEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.nameEdit)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.emailEdit = QtGui.QLineEdit(self.widget)
        self.emailEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.emailEdit.setAutoFillBackground(False)
        self.emailEdit.setInputMask("")
        self.emailEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.emailEdit.setObjectName("emailEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.emailEdit)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.UrlEdit = QtGui.QLineEdit(self.widget)
        self.UrlEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.UrlEdit.setAutoFillBackground(False)
        self.UrlEdit.setInputMask("")
        self.UrlEdit.setMaxLength(250)
        self.UrlEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.UrlEdit.setObjectName("UrlEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.UrlEdit)

        self.retranslateUi(formConfig)
        QtCore.QObject.connect(self.btnClose, QtCore.SIGNAL("clicked()"), formConfig.close)
        QtCore.QMetaObject.connectSlotsByName(formConfig)

    def retranslateUi(self, formConfig):
        formConfig.setWindowTitle(QtGui.QApplication.translate("formConfig", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("formConfig", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("formConfig", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("formConfig", "XML-RPC Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("formConfig", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("formConfig", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("formConfig", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("formConfig", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("formConfig", "URL", None, QtGui.QApplication.UnicodeUTF8))

import main_rc
