# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comment.ui'
#
# Created: Sun Apr 22 14:06:45 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CommentWindow(object):
    def setupUi(self, CommentWindow):
        CommentWindow.setObjectName("CommentWindow")
        CommentWindow.resize(581, 453)
        CommentWindow.setMinimumSize(QtCore.QSize(581, 453))
        CommentWindow.setMaximumSize(QtCore.QSize(581, 453))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/chat-quotes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CommentWindow.setWindowIcon(icon)
        self.frame = QtGui.QFrame(CommentWindow)
        self.frame.setGeometry(QtCore.QRect(10, 110, 561, 111))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 37, 40, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 37, 17))
        self.label_2.setObjectName("label_2")
        self.edit_email = QtGui.QLineEdit(self.frame)
        self.edit_email.setGeometry(QtCore.QRect(110, 70, 271, 27))
        self.edit_email.setObjectName("edit_email")
        self.edit_name = QtGui.QLineEdit(self.frame)
        self.edit_name.setGeometry(QtCore.QRect(110, 37, 271, 27))
        self.edit_name.setFrame(True)
        self.edit_name.setReadOnly(False)
        self.edit_name.setObjectName("edit_name")
        self.cb_status = QtGui.QCheckBox(self.frame)
        self.cb_status.setGeometry(QtCore.QRect(110, 10, 94, 22))
        self.cb_status.setObjectName("cb_status")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 61, 17))
        self.label_9.setObjectName("label_9")
        self.frame_2 = QtGui.QFrame(CommentWindow)
        self.frame_2.setGeometry(QtCore.QRect(10, 20, 561, 71))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 91, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 91, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(110, 10, 16, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(110, 40, 91, 17))
        self.label_6.setObjectName("label_6")
        self.lbl_post = QtGui.QLabel(self.frame_2)
        self.lbl_post.setGeometry(QtCore.QRect(130, 10, 421, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lbl_post.setFont(font)
        self.lbl_post.setText("")
        self.lbl_post.setObjectName("lbl_post")
        self.lbl_date = QtGui.QLabel(self.frame_2)
        self.lbl_date.setGeometry(QtCore.QRect(130, 40, 421, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.lbl_date.setFont(font)
        self.lbl_date.setText("")
        self.lbl_date.setObjectName("lbl_date")
        self.edit_comment = QtGui.QTextEdit(CommentWindow)
        self.edit_comment.setGeometry(QtCore.QRect(10, 220, 561, 171))
        self.edit_comment.setObjectName("edit_comment")
        self.btn_save = QtGui.QPushButton(CommentWindow)
        self.btn_save.setGeometry(QtCore.QRect(470, 410, 101, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon1)
        self.btn_save.setObjectName("btn_save")
        self.btn_close = QtGui.QPushButton(CommentWindow)
        self.btn_close.setGeometry(QtCore.QRect(360, 410, 101, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setObjectName("btn_close")
        self.progressBar = QtGui.QProgressBar(CommentWindow)
        self.progressBar.setGeometry(QtCore.QRect(10, 419, 71, 21))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.frame_3 = QtGui.QFrame(CommentWindow)
        self.frame_3.setGeometry(QtCore.QRect(9, 390, 561, 20))
        self.frame_3.setFrameShape(QtGui.QFrame.HLine)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")

        self.retranslateUi(CommentWindow)
        QtCore.QObject.connect(self.btn_close, QtCore.SIGNAL("clicked()"), CommentWindow.close)
        QtCore.QMetaObject.connectSlotsByName(CommentWindow)

    def retranslateUi(self, CommentWindow):
        CommentWindow.setWindowTitle(QtGui.QApplication.translate("CommentWindow", "Comment Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CommentWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CommentWindow", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_status.setText(QtGui.QApplication.translate("CommentWindow", "Approved", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CommentWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CommentWindow", "Comment for", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CommentWindow", "Date posted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CommentWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CommentWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save.setText(QtGui.QApplication.translate("CommentWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close.setText(QtGui.QApplication.translate("CommentWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

import main_rc
