# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sat Apr 21 20:42:08 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(796, 646)
        mainWindow.setAcceptDrops(False)
        mainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblComments = QtGui.QTableWidget(self.centralwidget)
        self.tblComments.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblComments.sizePolicy().hasHeightForWidth())
        self.tblComments.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tblComments.setFont(font)
        self.tblComments.setProperty("cursor", QtCore.Qt.PointingHandCursor)
        self.tblComments.setToolTip("")
        self.tblComments.setAutoFillBackground(False)
        self.tblComments.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tblComments.setFrameShadow(QtGui.QFrame.Sunken)
        self.tblComments.setLineWidth(1)
        self.tblComments.setMidLineWidth(0)
        self.tblComments.setAutoScroll(True)
        self.tblComments.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblComments.setTabKeyNavigation(False)
        self.tblComments.setAlternatingRowColors(True)
        self.tblComments.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblComments.setShowGrid(True)
        self.tblComments.setGridStyle(QtCore.Qt.NoPen)
        self.tblComments.setRowCount(0)
        self.tblComments.setColumnCount(6)
        self.tblComments.setObjectName("tblComments")
        self.tblComments.setColumnCount(6)
        self.tblComments.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblComments.setHorizontalHeaderItem(5, item)
        self.tblComments.horizontalHeader().setVisible(True)
        self.tblComments.horizontalHeader().setCascadingSectionResizes(True)
        self.tblComments.horizontalHeader().setDefaultSectionSize(100)
        self.tblComments.horizontalHeader().setHighlightSections(True)
        self.tblComments.horizontalHeader().setStretchLastSection(True)
        self.tblComments.verticalHeader().setVisible(False)
        self.tblComments.verticalHeader().setSortIndicatorShown(True)
        self.tblComments.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tblComments)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout.addWidget(self.statusLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMouseTracking(False)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(mainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setToolTip("")
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionRefresh = QtGui.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/arrow_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionConnection = QtGui.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnection.setIcon(icon1)
        self.actionConnection.setObjectName("actionConnection")
        self.actionPreferences = QtGui.QAction(mainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/cog_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon2)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtGui.QAction(mainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtGui.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/door_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon4)
        self.actionClose.setObjectName("actionClose")
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnection)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(mainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("activated()"), mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "WordPress Comments Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.setSortingEnabled(True)
        self.tblComments.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("mainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("mainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("mainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("mainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("mainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.tblComments.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("mainWindow", "Post Title", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar.setFormat(QtGui.QApplication.translate("mainWindow", "loading...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("mainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("mainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setToolTip(QtGui.QApplication.translate("mainWindow", "Refresh Comment list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnection.setText(QtGui.QApplication.translate("mainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnection.setToolTip(QtGui.QApplication.translate("mainWindow", "Edit Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("mainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setToolTip(QtGui.QApplication.translate("mainWindow", "Edit Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("mainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setToolTip(QtGui.QApplication.translate("mainWindow", "About WPC Desk", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("mainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setToolTip(QtGui.QApplication.translate("mainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

